Add pollen notification
lonestone/naonair pull request #144
Opened 2024-01-18 14:48 UTC by tatiana-lonestone

* [ETQ utilisateur, je dois recevoir une notification push lors du démarrage d'une nouvelle émission de pollens](https://app.clickup.com/t/86bwch8bh)
* [ETQ utilisateur, je peux choisir les pollens pour lesquels je souhaite recevoir une notification push](https://app.clickup.com/t/86bwch8mj)

2024-01-18 15:08 UTC, tatiana-lonestone commented on api/src/modules/pollenNotification/pollenNotification.controller.ts
> +  @Get(':fcmToken')
Johan : je ne sais pas si c'ets pertinent de mettre le fcm en param, dis moi ^^

2024-01-18 15:47 UTC, tatiana-lonestone commented on api/src/modules/pollenNotification/pollenNotification.service.ts
> +    const pollenAlerts = updatedPollen.filter((p) => p.newState === 1);
Ho, et il y a d'autres états, c'est pour ça que c'est un number 

```
{
    "0": "pas d'émission",
    "1": "émission en cours",
    "2": "émission terminée",
    "9": "non observable",
    "8": "en expérimentation"
}
```

2024-01-22 10:31 UTC, Johbrun commented on README.md
> +* Prod => "baseUrl": "https://naonair-api-staging.onrender.com/"
Nickel 👍 J'espère qu'on pourra changer un jour avec les bons domaines !

2024-01-23 09:30 UTC, smol approved these changes
Des petites babioles, rien de méchant

2024-01-23 09:30 UTC, smol commented on app/src/actions/pollen.ts
> +  return onlinePollen.map(pollen => {
Il faudrait mettre une p'tit commentaire pour expliquer ta fonction :)

2024-01-23 09:32 UTC, tatiana-lonestone commented on dtos/src/errors.dto.ts
> +  POLLEN_NOTIFICATION_DTO_FAILED = "Une update nécessite de renseigner le fcm token et un status",
Normalement, ce n'est pas une erreur qui est affichée. J'ai mis en Français pour garder en cohérence avec le reste, mais ça ne sert qu'à du log en théorie.

2024-01-23 09:35 UTC, tatiana-lonestone commented on app/src/actions/pollen.ts
> +  return onlinePollen.map(pollen => {
Done, merci !

2024-01-23 09:42 UTC, tatiana-lonestone commented on app/src/hooks/useNotifications.ts
> +    messaging().onMessage(async remoteMessage => {
C'est vrai, je change ça, merci !

2024-01-23 10:46 UTC, Johbrun requested changes

2024-01-23 10:46 UTC, Johbrun commented on api/src/modules/pollen/pollen.converter.ts
> +  public toDTO = (pollen: any): PollenDTO => ({
oh dommage le petit any ici :)

2024-01-23 10:46 UTC, Johbrun commented on api/src/modules/pollen/pollen.service.ts
> +    const pollens = await this.em.find(PollenEntity, {});
J'ai un doute, mais find() ne renvoi pas un tableau vide par défaut ?

2024-01-23 10:46 UTC, Johbrun commented on api/src/modules/pollen/pollen.service.ts
> +      // lastValueFrom get get Obsarvable datas and not all the observable.
Observable

2024-01-23 10:46 UTC, Johbrun commented on api/src/modules/pollenNotification/pollenNotification.controller.ts
> +    return await this.pollenService.findByToken(token);
pas besoin d'await :)

2024-01-23 10:46 UTC, Johbrun commented on api/src/modules/pollenNotification/pollenNotification.service.ts
> +    if (!fcmToken || isEnabled === undefined) {
normalement tu n'as plus besoin de ça, car ton type est validé par classValidator au sein du pipe

2024-01-23 12:54 UTC, Johbrun approved these changes

2024-01-23 15:15 UTC, merged