Initialisation des composant de création de parcours
lonestone/naonair pull request #166
Opened 2024-05-21 14:15 UTC by NoeGrangier

2024-05-22 14:53 UTC, tatiana-lonestone approved these changes

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/ios/aireal.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Hum, t'est sur de passer ça en automatic ?

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/atoms/ARMap.tsx
> +          {userLocationVisible && (
Le visible={userLocationVisible} ne suffit pas à ne pas afficher la map ?

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/molecules/ARBackButton.tsx
> -    marginTop: 3,
Attention, ARBackButton est utilisé sur plusieurs écrans :
![image](https://github.com/lonestone/naonair/assets/90247712/a7416fc1-3ff3-4e46-af86-29659b3829b9)
Tu as besoin que ça change partout ?

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/molecules/ARCommonHeader.tsx
> +    alignItems: 'center',
Meme remarque => Faut que ça change partout ?

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/molecules/ARFloatingBackButton.tsx
> +      <TouchableOpacity
Utilise un Pressable plutôt => https://reactnative.dev/docs/touchableopacity

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/organisms/ARParcourCreationSteps/ARParcourInitialStep.tsx
> +  const icon = useCallback(
Il me semble que, même si ils font à peu près la même chose, le hook useCallback est plus pour les fonctions et useMemo pour les valeurs.

C'est pas du tout de ça que parle cet article => https://www.joshwcomeau.com/react/usememo-and-usecallback/
Mais je l'aime bien et parler de useMemo/useCallback m'y a fait penser :D

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/components/templates/ARChooseItinerary.tsx
> -      <TouchableOpacity
Ha, je vois que tu as juste déplacé le composant ^^ Cool !
Mais un Pressable quand même, c'est plus actuel comme façon de faire sur React Native

2024-05-22 14:53 UTC, tatiana-lonestone commented on app/src/screens/NewParcours.tsx
> +      {!hasStarted && <ARFloatingBackButton />}
Plus de boutons back une fois que ça a commencé ?

2024-05-23 07:08 UTC, smol requested changes
Le projet devient un peu fat, il faudrait ajouter des alias dans le tsconfig afin d'eviter les '../../../../theme' par exemple.

Tu peux faire des alias pour le `theme`, les `atoms`, `organisms` et `hooks`

2024-05-23 07:08 UTC, smol commented on app/src/screens/NewParcours.tsx
> +const InitialPositionMarker = ({ position }: InitialPositionMarkerProps) => {
Il faudrait déplacer ce composants dans un dossier `/app/src/screens/NewParcours/components` afin d'eviter d'avoir un fichier avec trop de lignes

2024-05-23 07:08 UTC, smol commented on app/src/screens/NewParcours.tsx
> +  }, [setInitialPosition]);
Il faudrait déplacer ce morceaux de code dans un hooks `useUserPosition`

2024-05-23 07:08 UTC, smol commented on app/src/screens/NewParcours.tsx
> +  position?: Position;
Ce serait mieux que `position` soit non null et que tu fasse le check avant d'instancier le composant

2024-05-23 07:08 UTC, smol commented on app/src/components/templates/ARParcoursSteps.tsx
> +  const [step, setStep] = React.useState<Steps>(Steps.INITIAL);
Il faudrait importer directement `useState` pour que ce soit plus lisible :
`import React, {useState} from 'React'`

2024-05-23 08:45 UTC, NoeGrangier commented on app/src/components/atoms/ARMap.tsx
> +          {userLocationVisible && (
Pas d'après mes tests, si tu l'update à la volée, c'est pas mis à jour :/

2024-05-23 08:47 UTC, NoeGrangier commented on app/src/components/organisms/ARParcourCreationSteps/ARParcourInitialStep.tsx
> +  const icon = useCallback(
Yes je me suis trompé ici aha

2024-05-23 08:48 UTC, NoeGrangier commented on app/src/components/organisms/ARParcourCreationSteps/ARParcourInitialStep.tsx
> +  const icon = useCallback(
C'est bien une méthode que je memoise ici, ARButton n'accepte pas de JSX Element mais juste une callback qui en renvoi un

2024-05-23 08:50 UTC, NoeGrangier commented on app/src/screens/NewParcours.tsx
> +      {!hasStarted && <ARFloatingBackButton />}
C'est changé dans la prochaine PR

2024-05-23 08:51 UTC, NoeGrangier commented on app/src/screens/NewParcours.tsx
> +  position?: Position;
C'est un screen qui est instancier dans le Navigator, je vois pas trop ou je peux l'instancier avant

2024-05-23 08:56 UTC, NoeGrangier commented on app/src/screens/NewParcours.tsx
> +  position?: Position;
My bad j'avais pas de quel composant tu parlais

2024-05-23 09:07 UTC, NoeGrangier commented on app/src/components/molecules/ARBackButton.tsx
> -    marginTop: 3,
Sur iOS c'était chelou mais ouais sur android on a besoin de cette marge, je modifie ça ;)

2024-05-23 09:09 UTC, NoeGrangier commented on app/src/components/molecules/ARCommonHeader.tsx
> +    alignItems: 'center',
Ca par contre ouais, ça rend mieux partout aha

2024-05-23 09:25 UTC, tatiana-lonestone commented on app/src/components/atoms/ARMap.tsx
> +          {userLocationVisible && (
Ok. Chelou que ça fonctionne avec  `userLocationVisible && ...` et pas avec `visible`

Quelques pistes : 

* `userLocationVisible` n'a pas de valeur par défaut, ça peut foutre la merde quand le param n'est pas donné => `undefined` n'est ptet pas supporté par `MapboxGL.UserLocation`
* `userLocationVisible` est passé en dur à `true` sur plusieurs `ARMap` (genre dans `ARNavigationMapView` ya juste `userLocationVisible` sans value, sans possibilité d'update)

2024-05-23 09:27 UTC, tatiana-lonestone commented on app/src/components/organisms/ARParcourCreationSteps/ARParcourInitialStep.tsx
> +  const icon = useCallback(
Ho ? Très chelou, mais OK :)

2024-07-09 14:24 UTC, smol approved these changes

2024-07-09 14:39 UTC, merged