Added parcours recording
lonestone/naonair pull request #167
Opened 2024-07-03 10:17 UTC by NoeGrangier

PR un peu fat, l'ajout de la feature a trainé en longueur avec arret puis reprise puis re-arret, etc... J'aurais du mieux découper.
J'ai aussi integré des modfis demandé dans l'ancienne PR tel que les alias (qui touchent du coup a beaucoup beaucoup de fichiers)

2024-07-05 05:57 UTC, smol requested changes
Mise a part deux trois babioles, c'est un très bon taff. Je reject quand même pour avoir un suivi des corrections.

2024-07-05 05:57 UTC, smol commented on app/src/components/templates/ARParcoursSteps.tsx
> +  const onParcourCreationStarted = () => {
Utiliser un useCallback

2024-07-05 05:57 UTC, smol commented on app/src/components/templates/ARParcoursSteps.tsx
> +  const onParcourRecordingEnded = (eT: number, tD: number, aS: number) => {
Utiliser un useCallback

2024-07-05 05:57 UTC, smol commented on app/src/components/templates/ARParcoursSteps.tsx
> +  const onParcourValidated = (name: string) => {
Utiliser un useCallback

2024-07-05 05:57 UTC, smol commented on app/src/components/templates/ARRouteDetail.tsx
> +  const removeParcours = async (p: CustomParcours) => {
Utiliser un useCallback

2024-07-05 05:57 UTC, smol commented on app/src/components/templates/ARRouteDetail.tsx
> +  const formatDate = (date: string) => {
Utiliser un useMemo

2024-07-05 05:57 UTC, smol commented on app/src/hooks/useCustomParcours.ts
> +  const getParcours = async () => {
Utiliser un useCallback

2024-07-09 14:56 UTC, NoeGrangier commented on app/src/screens/NewParcours.tsx
> +  const onSave = async (
Ne fonctionne plus quand est mis dans un useCallback, le setTimeout n'est plus trigger

2024-07-10 05:56 UTC, smol approved these changes

2024-07-10 05:56 UTC, merged